# Generated by Django 5.2.5 on 2025-08-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_practicas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicas',
            old_name='objetico',
            new_name='objetivo',
        ),
    ]
