# Generated by Django 5.2.5 on 2025-08-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('objetivo', models.CharField(max_length=255)),
                ('contenido_html', models.TextField(help_text='Escribe HTML libre (puedes usar <h2>, <p>, <img>, etc.).')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
